apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kend-ken-cypress-1
  namespace: cypress
  labels:
    app: ken
spec:
  storageClassName: gp3
  dataSource:
    # volume snapshot content name here
    name:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi