apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ken-cypress
  namespace: cypress
  labels:
    app: ken-cypress
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: ken-cypress
  serviceName: ken-cypress
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app: ken-cypress
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: purpose
                    operator: In
                    values:
                      - cypress
      containers:
        - name: ken-cypress
          image: ubuntu:18.04
          imagePullPolicy: IfNotPresent
          command:
            - "sleep"
            - "31556736"
          volumeMounts:
            - name: kend
              mountPath: /kend
  volumeClaimTemplates:
    - metadata:
        name: kend
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "io2"
        resources:
          requests:
            storage: 3000Gi