apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: daily
  namespace: klaytn
spec:
  retention:
    maxCount: 2
  schedule: "0 0 * * *"
  snapshotTemplate:
    snapshotClassName: csi-aws-vsc