apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ken-cypress
  namespace: cypress
  labels:
    app: ken-cypress
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: ken-cypress
  serviceName: ken-cypress

  template:
    metadata:
      labels:
        app: ken-cypress
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: purpose
                    operator: In
                    values:
                      - cypress

      containers:
        - name: ken-cypress
          image: klaytn/klaytn:v1.8.1
          imagePullPolicy: IfNotPresent
          args:
            - "ken"
            - "--cypress"
            - "--metrics"
            - "--prometheus"
            - "--multichannel"
            - "--rpc"
            - "--rpcapi=admin,debug,klay,miner,net,personal,rpc,txpool,web3"
            - "--rpcport=8551"
            - "--rpcaddr=0.0.0.0"
            - "--rpccorsdomain=*"
            - "--rpcvhosts=*"
            - "--ws"
            - "--wsapi=admin,klay,miner,net,personal,rpc,txpool,web3"
            - "--wsaddr=0.0.0.0"
            - "--wsorigins=*"
            - "--datadir=/kend/cypress"
            - "--port=32323"
            - "--subport=32324"
            - "--srvtype=fasthttp"
            - "--verbosity=3"
            - "--syncmode=full"
            - "--maxconnections=10"
            - "--txpool.exec-slots.all=4096"
            - "--txpool.nonexec-slots.all=4096"
            - "--txpool.exec-slots.account=4096"
            - "--txpool.nonexec-slots.account=4096"
          ports:
            - containerPort: 8551
            - containerPort: 8552
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          volumeMounts:
            - name: kend
              mountPath: /kend

        - name: ken-healthchecker
          image: margintop3498/klaytn-healthchecker:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RPC_URL
              value: "http://localhost:8551"
            - name: MAX_BLOCK_DIFFERENCE
              value: "200"

  volumeClaimTemplates:
    - metadata:
        name: kend
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "io2"
        resources:
          requests:
            storage: 3000Gi