kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3-slow
provisioner: ebs.csi.aws.com
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  type: "gp3"
  iops: "3000"
  throughput: "250"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
