apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ken-reverseproxy
  namespace: proxy
spec:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 70
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ken-reverseproxy