apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ken-reverseproxy-hpa
  namespace: proxy
spec:
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 70
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ken-reverseproxy